name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install 🔧
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: pnpm install --frozen-lockfile

      - name: Build 🏗️
        run: pnpm run build

      - name: Generate variable name list 🏗️
        run: pnpm run generate-variable-names
